#!/usr/bin/env bash

app_name="mklukskey"

# Generate a random binary file to use as
# key for a LUKS encrypted volume
# $1: name of the volume
_mklukskey() {
  local \
    _volume="${1}" \
    _output_dir="${2}"
  dd \
    if=/dev/random \
    bs=32 \
    count=1 \
    of="${_output_dir}/${_volume}.key"
}

(( $# < 1 )) && \
  echo \
    "${app_name} <volume_name> (<output_dir>)"

_volume="${1}"
_output_dir="${2}"

[[ "${_output_dir}" == "" ]] && \
  _output_dir="$( \
    realpath \
    "$( \
      pwd)")"
  # or "/etc/keys""?
  #    ^ canonical one?
  #      cryptsetup-keys.ds?

_mklukskey \
  "${_volume}" \
  "${_output_dir}"
